@startuml
actor User as user
participant "Frontend" as front
participant "Backend" as back
participant "External Auth Site" as auth

user -> front: Request login
front -> back: Request login
back -> auth: Request login
auth --> user: Enter credentials
user -> auth: Login via 2FA
auth --> back: User authorized
back --> front: Display dashboard
@enduml
