@startuml
actor User as user
participant "Frontend" as front
participant "Backend" as back
participant "SQL Server" as sql

user -> front: Request logs
front -> back: Request logs
back -> sql: Request data
sql --> back: Return data
back --> front: Display logs
front --> user: Display logs

@enduml
