// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebServer.Data;

#nullable disable

namespace WebServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebServer.Models.AuditEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("WebServer.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualUse")
                        .HasColumnType("text");

                    b.Property<string>("ArnonaCodeShimush")
                        .HasColumnType("text");

                    b.Property<bool?>("ArnonaDebt")
                        .HasColumnType("boolean");

                    b.Property<string>("BldSivug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("BuildRights")
                        .HasColumnType("double precision");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("BuildingRightsNotUsed")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CanMunicipalityFix")
                        .HasColumnType("boolean");

                    b.Property<string>("Complaints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DamagePercentage")
                        .HasColumnType("numeric");

                    b.Property<bool?>("DangerousBuilding")
                        .HasColumnType("boolean");

                    b.Property<int?>("DaysSinceElectricityConsumption")
                        .HasColumnType("integer");

                    b.Property<int?>("DaysSinceWaterConsumption")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ElectricityConsumption")
                        .HasColumnType("numeric");

                    b.Property<string>("FiziNum")
                        .HasColumnType("text");

                    b.Property<string>("FldId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("FloorNum")
                        .HasColumnType("integer");

                    b.Property<double?>("FloorSum")
                        .HasColumnType("double precision");

                    b.Property<bool?>("ForPreservation")
                        .HasColumnType("boolean");

                    b.Property<string>("FutureUse")
                        .HasColumnType("text");

                    b.Property<string>("FutureYeud")
                        .HasColumnType("text");

                    b.Property<string>("GushM")
                        .HasColumnType("text");

                    b.Property<string>("GushS")
                        .HasColumnType("text");

                    b.Property<string>("HarigatBniya")
                        .HasColumnType("text");

                    b.Property<string>("HeterBniya")
                        .HasColumnType("text");

                    b.Property<string>("HezkaMove")
                        .HasColumnType("text");

                    b.Property<string>("HolderDetails")
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("InPilot")
                        .HasColumnType("boolean");

                    b.Property<string>("IntendedUse")
                        .HasColumnType("text");

                    b.Property<bool?>("IsUnitInEmptyBuilding")
                        .HasColumnType("boolean");

                    b.Property<string>("IsurShimushHoreg")
                        .HasColumnType("text");

                    b.Property<string>("KidumTichnunStatus")
                        .HasColumnType("text");

                    b.Property<string>("LandQuality")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<bool?>("LegalDispute")
                        .HasColumnType("boolean");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("MaintenanceStatus")
                        .HasColumnType("text");

                    b.Property<string>("MiuuniPosition")
                        .HasColumnType("text");

                    b.Property<string>("MivneNum")
                        .HasColumnType("text");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerDetails")
                        .HasColumnType("text");

                    b.Property<string>("OwnerPosition")
                        .HasColumnType("text");

                    b.Property<bool?>("OwnerUnderExecution")
                        .HasColumnType("boolean");

                    b.Property<string>("OwnershipType")
                        .HasColumnType("text");

                    b.Property<string>("ParcelM")
                        .HasColumnType("text");

                    b.Property<string>("ParcelS")
                        .HasColumnType("text");

                    b.Property<double?>("ParcelSize")
                        .HasColumnType("double precision");

                    b.Property<string>("ParcelTat")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrls")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PikuachAlBniya")
                        .HasColumnType("text");

                    b.Property<string>("PikuachKlali")
                        .HasColumnType("text");

                    b.Property<string>("PropertyNumber")
                        .HasColumnType("text");

                    b.Property<bool?>("Shiabud")
                        .HasColumnType("boolean");

                    b.Property<string>("ShikumStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("ShtachBantuySum")
                        .HasColumnType("double precision");

                    b.Property<string>("StandardMark")
                        .HasColumnType("text");

                    b.Property<string>("StatusSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StatusSummaryUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StreetCode")
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TkBinyanNum")
                        .HasColumnType("text");

                    b.Property<string>("Tofes4")
                        .HasColumnType("text");

                    b.Property<string>("TzavDangerBuilding")
                        .HasColumnType("text");

                    b.Property<string>("TzavShiputzFronts")
                        .HasColumnType("text");

                    b.Property<bool?>("WantToRent")
                        .HasColumnType("boolean");

                    b.Property<bool?>("WantToSell")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("WaterConsumption")
                        .HasColumnType("numeric");

                    b.Property<string>("WhatsInside")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("WebServer.Models.BuildingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("BuildingLogs");
                });

            modelBuilder.Entity("WebServer.Models.ExternalSystemSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("ExternalSystemSnapshots");
                });

            modelBuilder.Entity("WebServer.Models.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PendingTwoFactorCode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PendingTwoFactorExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PendingTwoFactorToken")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TwoFactorSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebServer.Models.BuildingLog", b =>
                {
                    b.HasOne("WebServer.Models.Building", "Building")
                        .WithMany("Logs")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebServer.Models.Users.AppUser", "CreatedByUser")
                        .WithMany("Logs")
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("Building");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("WebServer.Models.ExternalSystemSnapshot", b =>
                {
                    b.HasOne("WebServer.Models.Building", "Building")
                        .WithMany("ExternalSnapshots")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("WebServer.Models.Building", b =>
                {
                    b.Navigation("ExternalSnapshots");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("WebServer.Models.Users.AppUser", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
